#!/bin/sh
#
#            DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
#                    Version 2, December 2004
#
# Copyright (C) 2004 Sam Hocevar <sam@hocevar.net>
#
# Everyone is permitted to copy and distribute verbatim or modified
# copies of this license document, and changing it is allowed as long
# as the name is changed.
#
#            DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
#   TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION
#
#  0. You just DO WHAT THE FUCK YOU WANT TO.

echo "Content-Type: text/plain"
echo ""
echo "Reconnecting... "
echo -n "Old IP: "
ifconfig  pptp-vpn | grep 'inet addr' | cut -d: -f2 | awk '{ print $1}'
ifup wan
sleep 5
echo -n "New IP: "
ifconfig  pptp-vpn | grep 'inet addr' | cut -d: -f2 | awk '{ print $1}'
