#!/bin/sh

echo "Content-Type: text/plain"
echo ""
echo "Reconnecting... "

echo -n "Old IP: "
ifconfig  pptp-vpn | grep 'inet addr' | cut -d: -f2 | awk '{ print $1}'

ifup wan
sleep 5

echo -n "New IP: "
ifconfig  pptp-vpn | grep 'inet addr' | cut -d: -f2 | awk '{ print $1}'
